# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pnp < Formula
  desc "Pixel & Process Kubernetes deployment manager"
  homepage "https://github.com/fwartner/pnp"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fwartner/pnp/releases/download/v0.5.2/pnp_0.5.2_darwin_amd64.tar.gz"
      sha256 "f02ae32eb8aa551a7d8a924cfe1dd37a905d9d30ba70e35f3bb42697e6ee4650"

      define_method(:install) do
        bin.install "pnp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fwartner/pnp/releases/download/v0.5.2/pnp_0.5.2_darwin_arm64.tar.gz"
      sha256 "8bad0d42e3a7a0c59076ae0f4b3918d738059f4f4113eedac3081c35248df9a8"

      define_method(:install) do
        bin.install "pnp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwartner/pnp/releases/download/v0.5.2/pnp_0.5.2_linux_amd64.tar.gz"
      sha256 "e0130f7f1b63aeb739e7e2294abcf21745bd151865e7a5850750105446cd0af3"
      define_method(:install) do
        bin.install "pnp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwartner/pnp/releases/download/v0.5.2/pnp_0.5.2_linux_arm64.tar.gz"
      sha256 "ca0ee953a8ea3d19d4b314b1c9f78afea1b16a37fb850661e3ec8f204c12658d"
      define_method(:install) do
        bin.install "pnp"
      end
    end
  end
end
