# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pnp < Formula
  desc "Pixel & Process Kubernetes deployment manager"
  homepage "https://github.com/fwartner/pnp"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fwartner/pnp/releases/download/v1.1.0/pnp_1.1.0_darwin_amd64.tar.gz"
      sha256 "75adc559838dbd0897b0dfec859eddf4c6820a2f71b0018248903b7830daab64"

      define_method(:install) do
        bin.install "pnp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fwartner/pnp/releases/download/v1.1.0/pnp_1.1.0_darwin_arm64.tar.gz"
      sha256 "b99444ba5354d5025085636c2d1f1d3e1a148a129ae2371725ea9e5f73ec8fdb"

      define_method(:install) do
        bin.install "pnp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwartner/pnp/releases/download/v1.1.0/pnp_1.1.0_linux_amd64.tar.gz"
      sha256 "3aa174d1a14fee9f2bf7cc37162bea6c3adda6409e1ccc0547f90853961246a5"
      define_method(:install) do
        bin.install "pnp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwartner/pnp/releases/download/v1.1.0/pnp_1.1.0_linux_arm64.tar.gz"
      sha256 "7e60055385420dc20ad8c0934d2f4a7637e07afaaf936327efd07d8ba237abd2"
      define_method(:install) do
        bin.install "pnp"
      end
    end
  end
end
