# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prjct < Formula
  desc "Create project directory structures from YAML templates"
  homepage "https://github.com/fwartner/prjct"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fwartner/prjct/releases/download/v1.0.0/prjct_1.0.0_darwin_amd64.tar.gz"
      sha256 "f607e56f3c0934672915f2e59b939c6a906cc8641dfd2d53d0ab6df41448ee0e"

      def install
        bin.install "prjct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fwartner/prjct/releases/download/v1.0.0/prjct_1.0.0_darwin_arm64.tar.gz"
      sha256 "79a9e42436454f555bbccbdcab8de5047715566686bd957cb94f02fff0e20f01"

      def install
        bin.install "prjct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwartner/prjct/releases/download/v1.0.0/prjct_1.0.0_linux_amd64.tar.gz"
      sha256 "4df2baddf1b6792f0cb032a1840d990fb3879635d73e983235f6281030657726"
      def install
        bin.install "prjct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwartner/prjct/releases/download/v1.0.0/prjct_1.0.0_linux_arm64.tar.gz"
      sha256 "47f31ac7d6651149afa237260ee6f76791c2730a1381eeae42681b999d50c209"
      def install
        bin.install "prjct"
      end
    end
  end

  test do
    system "#{bin}/prjct", "version"
  end
end
