# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prjct < Formula
  desc "Create project directory structures from YAML templates"
  homepage "https://github.com/fwartner/prjct"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fwartner/prjct/releases/download/v1.0.2/prjct_1.0.2_darwin_amd64.tar.gz"
      sha256 "b69c0fd3fc66a9aef950209f1b16065ea65a080d8dcfe4f6aeba9c5e19aac7be"

      def install
        bin.install "prjct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fwartner/prjct/releases/download/v1.0.2/prjct_1.0.2_darwin_arm64.tar.gz"
      sha256 "2b759b0e37cf6576626a2011a1a8acb418da48a3e45afc7c20dfd4e1c9d956a5"

      def install
        bin.install "prjct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwartner/prjct/releases/download/v1.0.2/prjct_1.0.2_linux_amd64.tar.gz"
      sha256 "70a77686c394e96f660022029d2bc8e7f210e11e735672be33bb57336f32ec62"
      def install
        bin.install "prjct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fwartner/prjct/releases/download/v1.0.2/prjct_1.0.2_linux_arm64.tar.gz"
      sha256 "94676eddcf75e9c61d39456db81ca4ffafef9104fcc2b03bba88d0f06c7d0b30"
      def install
        bin.install "prjct"
      end
    end
  end

  test do
    system "#{bin}/prjct", "version"
  end
end
