name: Update Product Formula in Tap

on:
  repository_dispatch:
    types: [version-updated]

jobs:
  update-formula:
    name: Update Formula
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
      -
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      -
        name: Build formula_templater CLI
        run: |
          cd util/formula_templater && go build
      -
        name: Generate new formula
        if: ${{ github.event.client_payload.cask == 'false' }}
        run: |
          ./util/formula_templater/formula_templater ${{github.event.client_payload.name}} ${{github.event.client_payload.version}} ./util/formula_templater/config.hcl > ./Formula/${{github.event.client_payload.name}}.rb
     
      - 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump ${{github.event.client_payload.name}} ${{github.event.client_payload.version}}
          file_pattern: Formula/*.rb
          commit_user_name: fwartner
          commit_user_email: florian@wartner.io
